### PR TITLE
	fix bug related to \eqn and \deqn

### LINKED ISSUE #101: Error in build_site with deqn
The following error occurs when the ocs contain a line like this: 
`#' \deqn{\tilde{f}(x) = \frac{1}{n} ∑_{i=1}^n f(x, x_{iC}),}
`
Any ideas? 

Error in x[[length(x) - 1]] : 
  attempt to select less than one element in get1index <real>
In addition: There were 15 warnings (use warnings() to see them)
> traceback()
29: lapply(x, to_html, ...)
28: to_html.list(x, ...)
27: unlist(to_html.list(x, ...))
26: stri_c(..., sep = sep, collapse = collapse, ignore_null = TRUE)
25: str_c(unlist(to_html.list(x, ...)), collapse = "")
24: to_html.TEXT(x[[length(x) - 1]], ...)
23: stri_c(..., sep = sep, collapse = collapse, ignore_null = TRUE)
22: str_c("$$", to_html.TEXT(x[[length(x) - 1]], ...), "$$")
21: to_html.deqn(X[[i]], ...)
20: FUN(X[[i]], ...)
19: lapply(x, to_html, ...)
18: to_html.list(x, ...)
17: unlist(to_html.list(x, ...))
16: stri_c(..., sep = sep, collapse = collapse, ignore_null = TRUE)
15: str_c(unlist(to_html.list(x, ...)), collapse = "")
14: to_html.TEXT(x, ...)
13: parse_section(x, "Details", ...)
12: to_html.details(X[[i]], ...)
11: FUN(X[[i]], ...)
10: lapply(x, to_html, ...)
9: to_html.list(sections, topic = out$name, ...)
8: to_html(sections, topic = out$name, ...)
7: lapply(x, f)
6: unlist(lapply(x, f))
5: Filter(function(x) !is.null(x) & length(x), x)
4: compact(to_html(sections, topic = out$name, ...))
3: to_html.Rd_doc(rd, env = new.env(parent = globalenv()), topic = str_replace(basename(paths[[i]]), 
       "\\.html$", ""), pkg = pkg)
2: build_topics(pkg)
1: staticdocs::build_site(".", examples = F)

### PR DESCRIPTION
**Pull request by randy3k**
\eqn and \deqn have two formats: \eqn{latex}{ascii} and \eqn{latexascii}
they are correctly handled now

fix #101

### CODE REVIEW

**Comment by randy3k** [comment]
The test failure is not relevant.

File: R/to-html.r [hunk 1]
```diff
@@ -195,10 +195,11 @@ to_html.item <- function(x, ...) {
 #' @export
 to_html.eqn <- function(x, pkg, ...) {
   stopifnot(length(x) <= 2)
```
Comment (krlmlr) [inline R/to-html.r]: Is the `stopifnot()` call still needed here?

Comment (hadley) [inline R/to-html.r]: I think so - it will catch bad use of `\eqn{}` — I think it's still reasonable to check

**Comment by hadley** [comment]
Could you please a few tests using `rd2html()`?

**Comment by randy3k** [comment]
I have added some tests.

**Comment by hadley** [comment]
Thanks!
